add test for pmtiles generation

diff --git a/.github/workflows/test_pipelines.yaml b/.github/workflows/test_pipelines.yaml
--- a/.github/workflows/test_pipelines.yaml
+++ b/.github/workflows/test_pipelines.yaml
@@ -42,7 +42,16 @@ jobs:
     - name: Install dependencies
       run: |
         uv sync
-        uv pip install .[pmtiles]
 
     - name: Run tests with coverage
       run: uv run pytest -s --cov=. --cov-report=term-missing
+
+    - name: test dbt
+      run: |
+        cd dbt_
+        uv run dbt build || { echo "dbt build failed"; exit 1; }
+
+    - name: test pmtiles generation
+      run: |
+        uv pip install .[pmtiles]
+        uv run pipelines/run.py run generate_pmtiles --env dev
